spring.application.name=AiTarrot
server.port=8080
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true

anthropic.api.key=${ANTHROPIC_API_KEY:}
